version: '3.3'

networks:
    this_inception:

services:
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        restart: always
        container_name: mariadb
        env_file: .env
        volumes: 
            - /home/tde-cama/db-data:/var/lib/mysql
        networks:
            - this_inception
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        restart: always
        container_name: wordpress
        env_file: .env
        depends_on:
            - mariadb
        volumes: 
            - /home/tde-cama/wp-data:/var/www/localhost/htdocs
        networks:
            - this_inception
    nginx:
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        restart: always
        container_name: nginx
        volumes: 
            - /home/tde-cama/wp-data:/var/www/localhost/htdocs
        ports:
            - 443:443
        depends_on:
            - wordpress
            - mariadb
        networks:
            - this_inception
    
