version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ./server/src/data/postgres:/data/postgres
    env_file:
    - ./server/src/docker.env
    networks:
    - ft_transcendence
 
  nestjs:
        build:
            context: ./server
            dockerfile: Dockerfile
        restart: always
        container_name: nestjs
        depends_on:
            - postgres
        networks:
            - ft_transcendence
        ports:
          - "3000:3000"
  react:
        build:
            context: ./app
            dockerfile: Dockerfile
        restart: always
        container_name: react
        depends_on:
            - nestjs
        networks:
            - ft_transcendence
        ports:
          - "8080:8080"
 
networks:
  ft_transcendence:
    driver: bridge